Add check for minimum python version

diff --git a/psij-ci-setup b/psij-ci-setup
--- a/psij-ci-setup
+++ b/psij-ci-setup
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+MIN_PYTHON_VERSION="3.8"
+
 set -o pipefail
 
 if pip --version 2>&1 | egrep -q 'python 3\..*' >/dev/null 2>&1 ; then
@@ -280,6 +282,14 @@ check_key() {
     fi
 }
 
+check_python_version() {
+    VERSION=`$PYTHON --version | awk '{print $2}'`
+    FIRST=`echo -e "$VERSION\n$MIN_PYTHON_VERSION" | sort -V|head -n 1`
+    if [ "$FIRST" == "$VERSION" ]; then
+        echo "Error: PSI/J requires Python $MIN_PYTHON_VERSION or above. Your current version is $VERSION."
+        exit 2
+    fi
+}
 
 not_cached() {
     if [ ! -d .packages ]; then
@@ -341,6 +351,8 @@ while [ "$1" != "" ]; do
     fi
     shift
 done
+
+check_python_version
 
 MYPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
 cd "$MYPATH"
